server:
  port: 8769
spring:
  profiles: peer2
  application:
      name: eureka-server
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/